# Generated by Django 4.2.9 on 2024-01-23 13:21

import django.db.models.deletion
from django.db import migrations, models


def forward_func(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")
    Currency.objects.bulk_create(
        [
            Currency(code="EUR", name="Euro", symbol="€"),
            Currency(code="USD", name="United States Dollar", symbol="$"),
            Currency(code="GBP", name="British Pound Sterling", symbol="£"),
            Currency(code="CHF", name="Swiss Franc", symbol="CHF"),
        ]
    )


def reverse_func(apps, schema_editor):
    Currency = apps.get_model("currency", "Currency")
    Currency.objects.filter().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(db_index=True, max_length=25)),
                ("symbol", models.CharField(max_length=10)),
            ],
        ),
        migrations.RunPython(forward_func, reverse_func),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("priority", models.IntegerField()),
                ("address", models.CharField(max_length=250)),
                ("config", models.JSONField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("http", "HTTP Resource"),
                            ("json", "JSON File"),
                            ("csv", "CSV File"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                (
                    "rate_value",
                    models.DecimalField(
                        db_index=True, decimal_places=6, max_digits=18
                    ),
                ),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="currency.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["valuation_date"],
            },
        ),
    ]
