# Generated by Django 4.2.9 on 2024-01-23 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="currencyexchangerate",
            options={
                "ordering": ["valuation_date"],
                "verbose_name": "Currency Exchange Rate",
                "verbose_name_plural": "Currency Exchange Rates",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "ordering": ["priority"],
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
    ]
