# Generated by Django 4.2.9 on 2024-01-25 15:19

from django.db import migrations, models


def forward_func(apps, schema_editor):
    Provider = apps.get_model("currency", "Provider")
    Provider.objects.bulk_create(
        [
            Provider(
                name="Fixer",
                priority=3,
                address="http://data.fixer.io/api/",
                config={
                    "auth": {
                        "type": "query_param",
                        "access_key": "26845b1abd48de991e33fae064222eba",
                    },
                    "endpoints": {
                        "latest": {
                            "request": {
                                "args": {
                                    "access_key": "access_key",
                                    "source_currency_code": "base",
                                    "exchanged_currency_code": "symbols",
                                },
                                "path": "latest",
                            },
                            "response": {"path": "rates"},
                        },
                        "historical": {
                            "request": {
                                "args": {
                                    "access_key": "access_key",
                                    "source_currency_code": "base",
                                    "exchanged_currency_code": "symbols",
                                },
                                "path": "$date",
                            },
                            "response": {"path": "rates"},
                        },
                    },
                },
                resource_type="http",
                force_base_currency="EUR",
            ),
            Provider(
                name="JSON Mock",
                priority=2,
                address="assets/",
                config={
                    "auth": {},
                    "endpoints": {
                        "latest": {
                            "request": {
                                "path": "mock_latest.json",
                                "source_currency_code": "base",
                                "exchanged_currency_code": "symbols",
                            },
                            "response": {"path": "rates"},
                        },
                        "historical": {
                            "request": {
                                "path": "mock_historical.json",
                                "source_currency_code": "base",
                                "exchanged_currency_code": "symbols",
                            },
                            "response": {"path": "rates"},
                        },
                    },
                },
                resource_type="json",
                force_base_currency="",
            ),
            Provider(
                name="ExchangeRateApi",
                priority=1,
                address="http://api.exchangeratesapi.io/v1/",
                config={
                    "auth": {
                        "type": "query_param",
                        "access_key": "909bbd90133f9c20b6cf02335bc1e1c0",
                    },
                    "endpoints": {
                        "latest": {
                            "request": {
                                "path": "latest",
                                "args": {
                                    "access_key": "access_key",
                                    "source_currency_code": "base",
                                    "exchanged_currency_code": "symbols",
                                },
                            },
                            "response": {"path": "rates"},
                        },
                        "historical": {
                            "request": {
                                "path": "$date",
                                "args": {
                                    "access_key": "access_key",
                                    "source_currency_code": "base",
                                    "exchanged_currency_code": "symbols",
                                },
                            },
                            "response": {"path": "rates"},
                        },
                    },
                },
                resource_type="http",
                force_base_currency="EUR",
            ),
        ]
    )


def reverse_func(apps, schema_editor):
    Provider = apps.get_model("currency", "Provider")
    Provider.objects.filter().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_alter_currency_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="force_base_currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
